FROM golang:1.11.0-stretch

COPY . /go/src/github.com/clarkkkent/helper/user-service

WORKDIR /go/src/github.com/clarkkkent/helper/user-service

RUN go get -u github.com/golang/dep/cmd/dep
RUN dep init && dep ensure

RUN cd ./app && go build -i
RUN cd ./cli && go build -i

CMD go run ./app


