FROM golang:1.12.0 as builder

WORKDIR /go/src/github.com/clarkkkent/helper/user-cli

COPY . .

RUN go get -u github.com/golang/dep/cmd/dep
RUN dep init && dep ensure
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN mkdir /app

WORKDIR /app

COPY --from=builder /go/src/github.com/clarkkkent/helper/user-cli .

CMD ["./user-cli", "--username=Sergei --email=sergeleushin@gmail.com", "--password=Bethere4u!"]